# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import llm_pb2 as llm__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in llm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LLMServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SyncLogs = channel.unary_unary(
                '/llm.LLMService/SyncLogs',
                request_serializer=llm__pb2.SyncLogsRequest.SerializeToString,
                response_deserializer=llm__pb2.SyncLogsResponse.FromString,
                _registered_method=True)
        self.AppendLog = channel.unary_unary(
                '/llm.LLMService/AppendLog',
                request_serializer=llm__pb2.AppendLogRequest.SerializeToString,
                response_deserializer=llm__pb2.AppendLogResponse.FromString,
                _registered_method=True)
        self.QueryLLM = channel.unary_unary(
                '/llm.LLMService/QueryLLM',
                request_serializer=llm__pb2.QueryRequest.SerializeToString,
                response_deserializer=llm__pb2.QueryResponse.FromString,
                _registered_method=True)


class LLMServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SyncLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendLog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryLLM(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LLMServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SyncLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncLogs,
                    request_deserializer=llm__pb2.SyncLogsRequest.FromString,
                    response_serializer=llm__pb2.SyncLogsResponse.SerializeToString,
            ),
            'AppendLog': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendLog,
                    request_deserializer=llm__pb2.AppendLogRequest.FromString,
                    response_serializer=llm__pb2.AppendLogResponse.SerializeToString,
            ),
            'QueryLLM': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryLLM,
                    request_deserializer=llm__pb2.QueryRequest.FromString,
                    response_serializer=llm__pb2.QueryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'llm.LLMService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('llm.LLMService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LLMService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SyncLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llm.LLMService/SyncLogs',
            llm__pb2.SyncLogsRequest.SerializeToString,
            llm__pb2.SyncLogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppendLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llm.LLMService/AppendLog',
            llm__pb2.AppendLogRequest.SerializeToString,
            llm__pb2.AppendLogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryLLM(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llm.LLMService/QueryLLM',
            llm__pb2.QueryRequest.SerializeToString,
            llm__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
