# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raft.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'raft.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\x04raft\"[\n\x0bVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0b\x63\x61ndidateId\x18\x02 \x01(\t\x12\x14\n\x0clastLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0blastLogTerm\x18\x04 \x01(\x05\"1\n\x0cVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0bvoteGranted\x18\x02 \x01(\x08\"\xa9\x01\n\x08LogEntry\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\r\n\x05index\x18\x02 \x01(\x05\x12\x11\n\toperation\x18\x03 \x01(\t\x12\x0f\n\x07product\x18\x04 \x01(\t\x12\x12\n\nqty_change\x18\x05 \x01(\x05\x12\x0f\n\x07new_qty\x18\x06 \x01(\x05\x12\x10\n\x08username\x18\x07 \x01(\t\x12\x11\n\ttimestamp\x18\x08 \x01(\t\x12\x12\n\nrequest_id\x18\t \x01(\t\"\x98\x01\n\x14\x41ppendEntriesRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x10\n\x08leaderId\x18\x02 \x01(\t\x12\x14\n\x0cprevLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0bprevLogTerm\x18\x04 \x01(\x05\x12\x1f\n\x07\x65ntries\x18\x05 \x03(\x0b\x32\x0e.raft.LogEntry\x12\x14\n\x0cleaderCommit\x18\x06 \x01(\x05\"J\n\x15\x41ppendEntriesResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x12\n\nmatchIndex\x18\x03 \x01(\x05\">\n\x11\x46orwardRequestMsg\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\x12\r\n\x05token\x18\x03 \x01(\t\"4\n\x12\x46orwardResponseMsg\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\t2\xd2\x01\n\x0bRaftService\x12\x34\n\x0bRequestVote\x12\x11.raft.VoteRequest\x1a\x12.raft.VoteResponse\x12H\n\rAppendEntries\x12\x1a.raft.AppendEntriesRequest\x1a\x1b.raft.AppendEntriesResponse\x12\x43\n\x0e\x46orwardRequest\x12\x17.raft.ForwardRequestMsg\x1a\x18.raft.ForwardResponseMsgb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VOTEREQUEST']._serialized_start=20
  _globals['_VOTEREQUEST']._serialized_end=111
  _globals['_VOTERESPONSE']._serialized_start=113
  _globals['_VOTERESPONSE']._serialized_end=162
  _globals['_LOGENTRY']._serialized_start=165
  _globals['_LOGENTRY']._serialized_end=334
  _globals['_APPENDENTRIESREQUEST']._serialized_start=337
  _globals['_APPENDENTRIESREQUEST']._serialized_end=489
  _globals['_APPENDENTRIESRESPONSE']._serialized_start=491
  _globals['_APPENDENTRIESRESPONSE']._serialized_end=565
  _globals['_FORWARDREQUESTMSG']._serialized_start=567
  _globals['_FORWARDREQUESTMSG']._serialized_end=629
  _globals['_FORWARDRESPONSEMSG']._serialized_start=631
  _globals['_FORWARDRESPONSEMSG']._serialized_end=683
  _globals['_RAFTSERVICE']._serialized_start=686
  _globals['_RAFTSERVICE']._serialized_end=896
# @@protoc_insertion_point(module_scope)
